<?php
/**
 * SkillBridge - System Reports Generator
 */
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';

require_role('admin');

$db = Database::getInstance();

$reportsList = $db->fetchAll(
    "SELECT r.*, u.username 
     FROM reports r 
     LEFT JOIN users u ON r.generated_by_user_id = u.id 
     ORDER BY r.created_at DESC"
);

$pageTitle = "System Reports - Admin Portal";
include __DIR__ . '/../includes/header.php';
?>

<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4">
    <div>
        <h3 class="fw-bold mb-1"><i class="bi bi-file-earmark-pdf text-danger me-2"></i>Institutional System Reports</h3>
        <p class="text-muted small mb-0">Generate, print, and export CSV/PDF analytics reports</p>
    </div>
</div>

<div class="row g-4 mb-4">
    <!-- Quick Exporters -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm rounded-4 p-4 text-center h-100">
            <i class="bi bi-radar text-primary display-4 mb-2"></i>
            <h5 class="fw-bold">Skill Gap Matrix Report</h5>
            <p class="text-muted small">Export institutional skill deficit metrics and target level benchmarks.</p>
            <a href="<?= BASE_URL ?>reports/export.php?type=skill_gap" target="_blank" class="btn btn-outline-primary rounded-pill mt-auto">
                <i class="bi bi-download me-1"></i> Export Skill Gap Report
            </a>
        </div>
    </div>
    <div class="col-md-4">
        <div class="saas-card p-4 text-center h-100 d-flex flex-column">
            <i class="bi bi-pie-chart text-primary display-4 mb-2"></i>
            <h5 class="fw-bold text-dark">Institutional Skill Gap</h5>
            <p class="text-muted small">Comprehensive analysis of student skill deficiencies across departments.</p>
            <a href="<?= BASE_URL ?>reports/export.php?type=skill_gap" target="_blank" class="btn btn-primary rounded-pill mt-auto fw-semibold">
                <i class="bi bi-download me-1"></i> Export Skill Gap Report
            </a>
        </div>
    </div>
    <div class="col-md-4">
        <div class="saas-card p-4 text-center h-100 d-flex flex-column">
            <i class="bi bi-mortarboard text-success display-4 mb-2"></i>
            <h5 class="fw-bold text-dark">Student Performance</h5>
            <p class="text-muted small">Detailed student assessment scores, pass/fail status, and average grades.</p>
            <a href="<?= BASE_URL ?>reports/export.php?type=student_performance" target="_blank" class="btn btn-outline-success rounded-pill mt-auto fw-semibold">
                <i class="bi bi-download me-1"></i> Export Performance
            </a>
        </div>
    </div>
    <div class="col-md-4">
        <div class="saas-card p-4 text-center h-100 d-flex flex-column">
            <i class="bi bi-book text-warning display-4 mb-2"></i>
            <h5 class="fw-bold text-dark">Course Completion</h5>
            <p class="text-muted small">Overview of course enrollments, completion rates, and learning progress.</p>
            <a href="<?= BASE_URL ?>reports/export.php?type=course_completion" target="_blank" class="btn btn-outline-warning rounded-pill mt-auto fw-semibold">
                <i class="bi bi-download me-1"></i> Export Course Report
            </a>
        </div>
    </div>
</div>

<!-- Historical Generated Reports Log -->
<div class="saas-card overflow-hidden mt-4">
    <div class="saas-card-header">
        <h5 class="fw-bold text-dark mb-0"><i class="bi bi-archive me-2 text-primary"></i>Generated Reports Archive</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="saas-table align-middle mb-0">
                <thead>
                    <tr>
                        <th class="ps-4">Report Title</th>
                        <th>Type</th>
                        <th>Generated By</th>
                        <th>Date Generated</th>
                        <th class="pe-4 text-end">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($reportsList)): ?>
                        <tr>
                            <td colspan="5">
                                <div class="saas-empty-state">
                                    <div class="saas-empty-icon"><i class="bi bi-archive"></i></div>
                                    <h6 class="fw-bold text-dark mb-1">No historical report logs stored</h6>
                                    <p class="text-muted small mb-0">Generated PDF/CSV report logs will appear here.</p>
                                </div>
                            </td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($reportsList as $rep): ?>
                            <tr>
                                <td class="ps-4 fw-semibold text-dark"><?= htmlspecialchars($rep['title']) ?></td>
                                <td><span class="badge saas-badge-primary"><?= htmlspecialchars($rep['report_type']) ?></span></td>
                                <td><span class="small text-muted"><?= htmlspecialchars($rep['username'] ?? 'System') ?></span></td>
                                <td><span class="small text-muted"><?= format_date($rep['created_at']) ?></span></td>
                                <td class="pe-4 text-end">
                                    <a href="<?= BASE_URL ?>reports/export.php?type=<?= strtolower(str_replace(' ', '_', $rep['report_type'])) ?>" target="_blank" class="btn btn-outline-dark btn-sm rounded-pill px-3">
                                        <i class="bi bi-printer me-1"></i> Print / Download
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
